services:
  - type: web
    name: documind-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: frankfurt
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        sync: false
      - key: INTERNAL_AUTH_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: LOCAL_UPLOAD_DIR
        value: uploads
